name: clinic
services:
  # Инфраструктура
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.7
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - './config/keycloak/import:/opt/keycloak/data/import'
    ports:
      - '8083:8080'
    command: start-dev --import-realm
  tempo:
    image: grafana/tempo:2.3.1
    command: -config.file=/etc/tempo.yaml
    volumes:
      - './config/tempo/tempo.yaml:/etc/tempo.yaml'
    ports:
      - '3200:3200'
      - '9095:9095'
      - '4317:4317'
      - '4318:4318'
      - '9411:9411'
      - '14268:14268'
  loki:
    image: grafana/loki:2.9.4
    ports:
      - '3100:3100'
  grafana:
    image: grafana/grafana:10.2.4
    ports:
      - '3000:3000'
    volumes:
      - './data/grafana:/var/lib/grafana'
    user: '1000'
  victoria-metrics:
    image: victoriametrics/victoria-metrics:v1.93.12
    command: -promscrape.config=/promscrape.yaml
    volumes:
      - './config/victoria-metrics/promscrape_docker_compose.yaml:/promscrape.yaml'
    ports:
      - '8428:8428'
  clinic-db:
    image: postgres:16
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: clinic
      POSTGRES_PASSWORD: clinic
      POSTGRES_DB: clinic
  # Сервисы
  eureka-server:
    restart: always
    build:
      dockerfile: Dockerfile
      args:
        JAR_FILE: eureka-server/target/eureka-server-24.1.1-SNAPSHOT-exec.jar
      tags:
        - localhost:5000/clinic/eureka-server:24.1.1
    environment:
      SPRING_PROFILES_ACTIVE: cloudconfig
      LOKI: http://loki:3100
    ports:
      - '8761:8761'
  clinic-service:
    restart: always
    build:
      dockerfile: Dockerfile
      args:
        JAR_FILE: clinic-service/target/clinic-service-24.1.1-SNAPSHOT-exec.jar
      tags:
        - localhost:5000/clinic/clinic-service:24.1.1
    environment:
      SPRING_PROFILES_ACTIVE: cloudconfig, gateway
      LOKI: http://loki:3100
  user-app:
    restart: always
    build:
      dockerfile: Dockerfile
      args:
        JAR_FILE: user-app/target/user-app-24.1.1-SNAPSHOT-exec.jar
      tags:
        - localhost:5000/clinic/customer-app:24.1.1
    environment:
      SPRING_PROFILES_ACTIVE: cloudconfig, gateway
      LOKI: http://loki:3100
  manager-app:
    restart: always
    build:
      dockerfile: Dockerfile
      args:
        JAR_FILE: manager-app/target/manager-app-24.1.1-SNAPSHOT-exec.jar
      tags:
        - localhost:5000/clinic/manager-app:24.1.1
    environment:
      SPRING_PROFILES_ACTIVE: cloudconfig, gateway
      LOKI: http://loki:3100
  api-gateway:
    restart: always
    build:
      dockerfile: Dockerfile
      args:
        JAR_FILE: api-gateway/target/api-gateway-24.1.1-SNAPSHOT-exec.jar
      tags:
        - localhost:5000/clinic/api-gateway:24.1.1
    environment:
      SPRING_PROFILES_ACTIVE: cloudconfig
      LOKI: http://loki:3100
    ports:
      - '8086:8086'


