kupang:
  services:
    clinic:
      uri: http://127.0.0.1:8081
      registration-id: keycloak

spring:
  application:
    name: clinic-manager-service
  datasource:
    url: jdbc:postgresql://localhost:5443/manager
    username: manager
    password: manager
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://host.docker.internal:8083/realms/clinic
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: manager-app
            client-secret: JJCWFPwDdIovMgegrvfF7hSeMoDv61ih
            scope:
              - openid
              - view_clinic_users
              - view_clinic_specialities
              - view_clinic_vets
              - view_clinic_genders
              - edit_clinic_users
              - edit_clinic_specialities
              - edit_clinic_vets
              - edit_clinic_genders
              - microprofile-jwt

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
  zipkin:
    tracing:
      endpoint: http://172.18.75.148:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0