server:
  port: 8085

kupang:
  services:
    clinic:
      uri: http://127.0.0.1:8081
      registration-id: keycloak

spring:
  application:
    name: clinic-user-service
  datasource:
    url: jdbc:postgresql://localhost:5442/users
    username: user
    password: user
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://host.docker.internal:8083/realms/clinic
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: user-app
            client-secret: JKkD5GiXNKznILRD5xGpgikQqdpX9mC8
            scope:
              - openid
              - microprofile-jwt

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
  zipkin:
    tracing:
      endpoint: http://172.18.75.148:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0