server:
  port: 8081

spring:
  application:
    name: clinic-db-service
  datasource:
    url: jdbc:postgresql://localhost:5445/clinic
    username: clinic
    password: clinic
  flyway:
    schemas:
      - public
      - clinic
  jpa:
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://host.docker.internal:8083/realms/clinic

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
  zipkin:
    tracing:
      endpoint: http://172.18.75.148:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    sql: info