spring:
  datasource:
    url: jdbc:postgresql://localhost:5445/clinic
    username: clinic
    password: clinic
  flyway:
    schemas:
      - public
      - clinic
  jpa:
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/realms/clinic

server:
  port: 8081
logging:
  level:
    sql: info